### ISSUE TITLE
Player2 ships are prepopulated in placement screen

### ISSUE THREAD

**Issue by TannerAMay** [JayTSmith/battleship-lua#27]
After selecting pvp and going to the placement screen, player2 already has ships on the board even though the player has not placed them. The AI ship placement is not in the correct order.

**Comment by JayTSmith** [comment]
The reason this happens is that the random placement for the ships is done in GameScreen's new function. All of the screens are constructed upon boot up.

**Comment by TannerAMay** [comment]
Fixing in the next commit. It will be coupled with moving AI to its own file
